apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: front-end
    app: nginx
spec: 
  replicas: 3
  selector:   
    matchLabels:
      app: myapp
      type: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine

# kubectl create -f deployment.yml

# kubectl rollout status deployment/myapp-deployment

# kubectl rollout history deployment/myapp-deployment

# kubectl apply -f deployment.yml
