apiVersion: v1
kind: Service
metadata:
  name: myapp-service

spec:
  type: ClusterIp
  ports:
    - port: 80
      targetPort: 80
  # type: NodePort # can be clusterIP, LoadBalancer, NodePort, or ExternalName
  # ports:
  #   - port: 80 # the port on the service. 
  #     targetPort: 80  #the port of the pod
  #     nodePort: 30008 # the port which gets exposed or gets accessed  by the user. any value between 30000 and 32767
  selector:
    app: myapp
    tier: front-end
  


  ## kubectl create -f service-definition.yml
  ## kubectl get services
  ## curl http://192.168.1.2:30008